"""remove level column use total_xp

Revision ID: 7e20dba6c806
Revises: a10a05e5a041
Create Date: 2026-03-20 16:06:12.719726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e20dba6c806'
down_revision: Union[str, None] = 'a10a05e5a041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_xp', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('users', 'xp')
    op.drop_column('users', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('xp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'total_xp')
    # ### end Alembic commands ###
